apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cyfkzzbxz-java-springboot
  janus-idp.io/tekton: cyfkzzbxz-java-springboot
  backstage.io/kubernetes-id: cyfkzzbxz-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cyfkzzbxz-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
